apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: app
          image: conglt/server-study-chain
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_CONTAINER
              value: mongodb://db:27017/studychain
          imagePullPolicy: Always
