apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-ca
  template:
    metadata:
      labels:
        app: academy-ca
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
      containers:
        - name: academy-ca
          image: hyperledger/fabric-ca:1.4.4
          imagePullPolicy: IfNotPresent
          command:
            [
          		'sh',
          		'-c',
              'fabric-ca-server start -b admin:adminpw -d'
            ]
          env:
            - name: TZ
              value: 'America/Sao_Paulo'
            - name: FABRIC_CA_SERVER_CA_NAME
              value: 'ca.academy.certificate.com'
            - name: FABRIC_CA_SERVER_DEBUG
              value: 'true'
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: 'false'
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/academy.certificate.com/ca/ca.academy.certificate.com-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/academy.certificate.com/ca/62b1c120285493236a09a5ad3416f386d7e8f07a787e93f79f2c542037ace904_sk
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/academy.certificate.com/ca/ca.academy.certificate.com-cert.pem
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/academy.certificate.com/ca/62b1c120285493236a09a5ad3416f386d7e8f07a787e93f79f2c542037ace904_sk
            - name: GODEBUG
              value: 'netdns=go'
          volumeMounts:
            - mountPath: /fabric
              name: fabricfiles
