apiVersion: v1
kind: Service
metadata:
  name: certificate-academypeer1
  labels:
    run: certificate-academypeer1
spec:
  type: ClusterIP
  selector:
    name: academypeer1
  ports:
    - protocol: TCP
      port: 30110
      name: grpc
    - protocol: TCP
      port: 30111
      name: events
