apiVersion: v1
kind: Service
metadata:
  name: certificate-orderer
  labels:
    run: certificate-orderer
spec:
  type: ClusterIP
  selector:
    name: orderer
  ports:
    - protocol: TCP
      port: 31010
      name: grpc
