apiVersion: v1
kind: Service
metadata:
  name: certificate-explorer-app-svc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 31317
      port: 9090
      targetPort: 8080
  selector:
    app: explorer
