apiVersion: v1
kind: Service
metadata:
  name: certificate-studentpeer0
  labels:
    run: certificate-studentpeer0
spec:
  type: ClusterIP
  selector:
    name: studentpeer0
  ports:
    - protocol: TCP
      port: 30110
      name: grpc
    - protocol: TCP
      port: 30111
      name: events
